### ISSUE TITLE
How do I get the data for "Data Setup"?

### ISSUE THREAD

**Issue by julianpeeters** [dhgarrette/ccg-parsing-2015#1]
Hi, 

Interesting project, thanks for open sourcing the code you used.

[Here in the read me](https://github.com/dhgarrette/2015-ccg-parsing#data-setup) we're instructed to put the data in the correct directory structure. What data? Where does it come from?

Thanks

**Comment by dhgarrette** [comment]
Thanks!

The Italian data is freely available from here: http://www.di.unito.it/~tutreeb/CCG-TUT/

Unfortunately the English and Chinese data are not freely available.  They must be obtained from the LDC and require licenses.  If your institution has the required licenses, then you should be able to download them.  See https://catalog.ldc.upenn.edu/LDC2005T13 for English and http://www.ldc.upenn.edu/Catalog/CatalogEntry.jsp?catalogId=LDC2007T36 for Chinese.  Note that the Chinese data must be run through a conversion process using software described here: https://github.com/jogloran/cnccgbank/blob/master/README

**Comment by julianpeeters** [comment]
Great, I'll give it a shot.
